### ISSUE TITLE
Disable leave buffer, cool, but on return it kills it anyways

### ISSUE THREAD

**Issue by shmup** [lilydjwg/colorizer#34]
I don't want this to run automatically, so I don't configure it to do so

But minimally I'd like to be able to `:CT` and turn 'em on, leave the buffer (and set the appropriate setting so that doesn't toggle off), and when I return, the colors should still be visible, I feel

Is this intentionally not done this way, or, is there something specific about my setup that could be doing it?

e.g.

1. `:CT`
2. navigate to another pane, but also having `let g:colorizer_disable_bufleave = 1`
3. return to colored pane, and it kills the colors
4. in this scenario if I `:CT` again, it doesn't turn 'em back on, that is technically toggling off I think? Because doing an additional `:CT` will turn them back on

I tried to capture that experience here

http://showterm.io/53cd5541834dd54b2944f

**Comment by lilydjwg** [comment]
What is `g:colorizer_disable_bufleave`? This plugin doesn't have that setting. Maybe you are using a different one?

**Comment by shmup** [comment]
Haha, dang, you're right!

https://github.com/chrisbra/Colorizer

Cheers, will close :P
