### ISSUE TITLE
All colors show as shades of grey

### ISSUE THREAD

**Issue by Ingvix** [lilydjwg/colorizer#38]
I don't think it's a bug in the plugin but I just don't know how to figure this out myself. Other colors show correctly but not the ones created by this plugin. I had similar problem with vim-css-color before. My terminal supports 254 colors so that shouldn't be an issue.

**Comment by lilydjwg** [comment]
What is your terminal and `:set term?` output?

**Comment by Ingvix** [comment]
My terminal is st but at least Neovim don't know that option. As I tabbed the option 'term' I found option 'termguicolors' which apparently was off and after setting it on the colors appear as they should. So I guess this issue is solved with that. So thanks for that accidental help.
